### ISSUE TITLE
User can view top performing stocks

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/ajax-project#1]
## 📐 Functionality

Create a table of the current day's 3 top performing stocks using data from the Tradier API.

## ✅ Task List

- [x] Create a header in HTML and CSS that shows the name of the application.
- [x] Create a search bar.
- [x] Create a table that shows the top 3 performing stocks.
- [x] Use the MarketStack API to get the last stock price.
