### ISSUE TITLE
User can view a stock’s details

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/ajax-project#3]
## 📐 Functionality

Display the symbol, last price, and change of the stock that was searched.

## ✅ Task List

- [x] Listen for `'submit'` events.
- [x] Assign the search value into the stock data model when the form is submitted.
- [x] Reset the search input when the form is submitted.
- [x] Use the Tradier API to update the top-performing stocks box to display the searched stock's name, symbol, last price, and change.
- [x] Hide the unused table elements.
