### ISSUE TITLE
User can view a stock’s recent news

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/ajax-project#4]
## 📐 Functionality

Display the searched stock's top three headlines.

## ✅ Task List

- [ ] Add a new div to the HTML to display the stock's top three headlines
- [ ] Use the NewsAPI to display the searched stock's top three headlines
- [ ] Listen for 'click' events on the stock search header and reload the page when it is clicked
- [ ] Display error message when user enters a stock name that cannot be found.
